function alert.help
	echo 'Welcome to alert help'
	echo ''
	echo 'The following are the only ways you can use this app:'
	echo '----------------------------------------------------------------------------------------'
	echo 'alert  [-h/--help|-m/--message=+|-u/--urgency=+|-b/--beep=+'
	echo ''
	echo '           ..........................main.............................'
	echo ''
	echo '   -t/--title      - The title of the alert'
	echo '   -m/--message    - The message to be displayed from the alert function'
	echo '   -u/--urgency    - The urgency of said alert'
	echo '   -b/--beep       - if set, will play beep. If set then plays a beep. various options for plating a beep will be implemented'
	echo ''
	echo ''
	echo ''
	echo ''
	echo 'AUTHOR: AGW'
end