function countdown.help
	echo 'Welcome to countdown help'
	echo ''
	echo 'Displays time in a human readable fasion. Only supports seconds for now'
	echo '----------------------------------------------------------------------------------------'
	echo 'show_time [-h/--help|-s=+|-M=+|-H=+|-D=+|-t|-d]'
	echo ''
	echo '           ..........................main.............................'
	echo ''
	echo '   -h/--help       - Displays this message and quits'
	echo '   -t/--show-time  - Displays time prettyfied and exits'
	echo '   -d/--delay      - Countdown, where the timer only updates every x seconds'
	echo ''
	echo '           ......................time commands.........................'
	echo ''
	echo '   -s/--seconds    - Input seconds you want to have converted to d/h/m/s'
	echo '   -M/--minuts     - Input minuts you want to have converted to d/h/m/s'
	echo '   -H/--hours      - Input hours you want to have converted to d/h/m/s'
	echo '   -D/--days       - Input days you want to have converted to d/h/m/s'
	echo ''
	echo '----------------------------------------------------------------------------------------'
	echo ''
	echo ''
	echo ''
	echo 'AUTHOR: AGW'
end