function pull_master.help
	echo 'Welcome to Pull_master help'
	echo ''
	echo 'This will make sure that all shops etc are up to snuff with master. .'
	echo '----------------------------------------------------------------------------------------'
	echo 'pull_master  [-h/--help|-r/--restart|-R/--rebuild|--excludeflex|--excludeshop|--excludecrawler]'
	echo ''
	echo '           ..........................main.............................'
	echo ''
	echo '   -r/--restart    - Toggle if we should restart the docker images'
	echo '   -R/--rebuild    - Toggle if we should rebuild the docker images for flex, and shop'
	echo '   -h/--help       - Displays this message and quits'
	echo '   --exclude*      - Excludes the given git repository from being pulled from master '
	echo ''
	echo '----------------------------------------------------------------------------------------'
	echo ''
	echo ''
	echo ''
	echo 'AUTHOR: AGW'
end