function rdp.help
	echo 'Welcome to RDP help'
	echo ''
	echo 'The following are the only ways you can use this app:'
	echo '----------------------------------------------------------------------------------------'
	echo 'rdp  [-h/--help|-c/--consignor|-l/--labtop]'
	echo ''
	echo '           ..........................main.............................'
	echo ''
	echo '   -c/--consignor  - Opens a remote desktop to consignor, the windows server located at AO'
	echo '   -l/--labtop     - Not implimented'
	echo '   -h/--help       - Displays this message and quits'
	echo ''
	echo '           ........................internal...........................'
	echo '   --user    [arg] - Change user, default is agw'
	echo '   --width   [arg] - The width of the remote desktop'
	echo '   --height  [arg] - The height of the remote desktop'
	echo '   --nofonts		 - if present, fonts will not be shown'
	echo '   --wallpaper     - if present, wallpaper will be shown'
	echo '   --noclipboard     - if present, clipboard will not be shared'
	echo '   -e/--exag [arg] - extra args that will not be parsed by this program. Not recommended.'
	echo '----------------------------------------------------------------------------------------'
	echo ''
	echo ''
	echo ''
	echo 'AUTHOR: AGW'
end