function show_time.help
	echo 'Welcome to show_time help'
	echo ''
	echo 'Displays time in a human readable fasion. Only supports seconds for now'
	echo '----------------------------------------------------------------------------------------'
	echo 'show_time [-h/--help|-s]'
	echo ''
	echo '           ..........................main.............................'
	echo ''
	echo '   -s              - Input seconds you want to have converted to d/h/m/s'
	echo '   -h/--help       - Displays this message and quits'
	echo ''
	echo '----------------------------------------------------------------------------------------'
	echo ''
	echo ''
	echo ''
	echo 'AUTHOR: AGW'
end