function update_flex_and_shop.help
	echo 'Welcome to Update flex and shop help'
	echo ''
	echo 'This will schedule an update for the shop and/or flex. These will run async.'
	echo '----------------------------------------------------------------------------------------'
	echo 'update_flex_and_shop  [-h/--help|-t/--time|-s/--shop|-f/--flex|-y/--force-yes]'
	echo ''
	echo '           ..........................main.............................'
	echo ''
	echo '   -f/--flex       - Toggelse flex db to be updated'
	echo '   -s/--shop       - Toggelse shop db to be updated'
    echo '   -y/--force-yes  - No need to accept the request'
	echo '   -t/--time       - Set time for when to update'
	echo '   -h/--help       - Displays this message and quits'
	echo ''
	echo '----------------------------------------------------------------------------------------'
	echo ''
	echo ''
	echo ''
	echo 'AUTHOR: AGW'
end